function [BW_out,properties] = filterRegions(BW_in)
%filterRegions Filter BW image using auto-generated code from imageRegionAnalyzer app.

% Auto-generated by imageRegionAnalyzer app on 07-May-2024
%---------------------------------------------------------

% Convert input image to binary
BW_binary = imbinarize(BW_in);

% Remove portions of the image that touch an outside edge.
BW_clearborder = imclearborder(BW_binary);

% Fill holes in regions.
BW_filled = imfill(BW_clearborder, 'holes');

% Filter image based on image properties.
BW_filtered = bwpropfilt(BW_filled,'Area',[200, 19490]);

% Get properties.
properties = regionprops(BW_filtered, {'Area', 'Eccentricity', 'EquivDiameter', 'EulerNumber', 'MajorAxisLength', 'MinorAxisLength', 'Orientation', 'Perimeter'});

% Convert output back to uint8 if needed
BW_out = uint8(BW_filtered) * 255;
end
